### ISSUE TITLE
[NOTICE] Unraid template created

### ISSUE THREAD

**Issue by nwithan8** [ozencb/couchtube#2]
Hey, great application! I went ahead and made an Unraid template for the Community Apps Store so Unraid users can easily install and setup this Docker container on their servers. Just a heads up in case some users start visiting this repository in regards to this app running on their Unraid servers.

**Comment by ozencb** [comment]
Awesome! Thanks a lot for the heads up, appreciate it

**Comment by webfiles** [comment]
Many thanks for creating the template for Unraid nwithan8.  

Any idea why the docker machine is not starting - see below: 

It is complaining about missing environment file and the videos.json file.

Installation:
—————-
Add Container

Pulling image: ghcr.io/ozencb/couchtube:latest
IMAGE ID [1851569316]: Pulling from ozencb/couchtube.  IMAGE ID [da9db072f522]: Pulling fs layer. Downloading 100% of 3 MB. Download complete. Extracting. Pull complete.  IMAGE ID [e0826806493b]: Pulling fs layer. Downloading 100% of 4 MB. Verifying Checksum. Download complete. Extracting. Pull complete.  IMAGE ID [6eb0202805d3]: Pulling fs layer. Downloading 100% of 111 B. Verifying Checksum. Download complete. Extracting. Pull complete.  IMAGE ID [4f4fb700ef54]: Pulling fs layer. Downloading 100% of 32 B. Download complete. Extracting. Pull complete.  IMAGE ID [336d74ea8399]: Pulling fs layer. Downloading 100% of 8 MB. Verifying Checksum. Download complete. Extracting. Pull complete.  IMAGE ID [6e58edd752c9]: Pulling fs layer. Downloading 100% of 667 KB. Verifying Checksum. Download complete. Extracting. Pull complete.  IMAGE ID [d4a3fccf6d69]: Pulling fs layer. Downloading 100% of 2 KB. Verifying Checksum. Download complete. Extracting. Pull complete.  Status: Downloaded newer image for ghcr.io/ozencb/couchtube:latest  TOTAL DATA PULLED: 16 MB

Command execution
docker run
  -d
  --name='CouchTube'
  --net='bridge'
  --pids-limit 2048
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME=“########"
  -e HOST_CONTAINERNAME="CouchTube"
  -e 'READONLY_MODE'='false'
  -e 'PORT'='8363'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8363]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/couchtube-icon.png'
  -p '8363:8363/tcp' 'ghcr.io/ozencb/couchtube:latest' 
b24aa6f4b6c0549cbef56f92f46c85d927b9b02e911b886fccbbc7c35a13b370  The command finished successfully!

Log:
——
2024/12/31 09:26:10 No .env file found, relying on system environment variables
2024/12/31 09:26:10 Created new SQLite database file at couchtube.db
2024/12/31 09:26:10 Database initialized and tables created successfully.
2024/12/31 09:26:10 Failed to open file /videos.json: open /app/videos.json: no such file or directory
2024/12/31 09:26:10 open /app/videos.json: no such file or directory

Same issue with the stable branch.  Unraid version is 6.12.13

**Comment by nwithan8** [comment]
@ozencb Is there a `videos.json` file that needs to be mapped into the container?

**Comment by ozencb** [comment]
@nwithan8 Yes, that file is used as the initial data source for channels and videos

**Comment by nwithan8** [comment]
@ozencb Looking at the [Docker compose](https://github.com/ozencb/couchtube/blob/c1297a91f985b8390a4e8084ce5d9aaddf0b0c30/docker-compose.yml#L10), there's a `videos.json` file that gets mounted into the container at `/app/data/videos.json`, but the `JSON_FILE_PATH` variable indicates the file should be at `/data/videos.json`, and yet this log says the file `/app/videos.json` is missing. So we have three different paths we're dealing with here.

**Comment by webfiles** [comment]
Thanks @nwithan8, I even tried removing and reinstalling it with JSON_FILE_PATH set to /app/data/videos.json but to no avail.

**Comment by nwithan8** [comment]
Looking for clarification from @ozencb

**Comment by ozencb** [comment]
Hello friends! I am afraid I have virtually zero time to keep working on this project, ATM.
I remember having some trouble getting everything (fly.io, local instances) working together for file paths, so yeah, it needed some more work. Please feel free to open pull requests
