### ISSUE TITLE
The application stops playing videos if the video list contains an unavailable video

### ISSUE THREAD

**Issue by codenamek83** [ozencb/couchtube#4]
I am currently exploring and testing the application to assess how I can utilize it. One of my tests involves exporting a YouTube playlist containing music videos to a JSON file. However, when a video is unavailable (with the error message 'Video Unavailable, Watch on YouTube'), the application fails to proceed to the next video in the playlist.

For instance, including this song in the video list will break the loop: mZ6VezKMoRY

This error message doesn't appear for every failure; instead, it occurs randomly.
![Screenshot from 2024-11-11 18-17-36](https://github.com/user-attachments/assets/b5bbbf9f-8f4f-4bbf-9480-a7aafe668a00)

Please let me know if you need any additional information.

**Comment by ozencb** [comment]
Shoot, let me check. 

There already is an invalidation process where the video us deleted from the DB if it encounters these errors, but it `READONLY_MODE` has to be turned off. Is it turned off for you? If so, can you check if the request succeeeds or not please?

**Comment by ozencb** [comment]
There was an issue with video invalidation as well, which should be fixed now. Can you pull the latest image before trying this?

**Comment by codenamek83** [comment]
Thank you for the quick fix. I’ve tested the new image, and it seems the 'video invalidation' process is functioning correctly now. I uploaded a JSON file with 69 videos, but only 55 were added to the couchtube.db. The loop is now working as expected.

However, why is the application unable to validate videos like 'rGedjDnQ9cw' or 'mZ6VezKMoRY', even though I can view them on YouTube but not in Couchtube?

**Comment by ozencb** [comment]
Embedding is not allowed for some videos, unfortunately. The application prints out an error message on the browser console for these with error codes as well.

 From official docs:

```

2 – The request contains an invalid parameter value. For example, this error occurs if you specify a video ID that does not have 11 characters, or if the video ID contains invalid characters, such as exclamation points or asterisks.
5 – The requested content cannot be played in an HTML5 player or another error related to the HTML5 player has occurred.
100 – The video requested was not found. This error occurs when a video has been removed (for any reason) or has been marked as private.
101 – The owner of the requested video does not allow it to be played in embedded players.
150 – This error is the same as 101. It's just a 101 error in disguise!

```

**Comment by codenamek83** [comment]
Hello @ozencb, thanks for checking the issue. I did some further checks to satisfy my curiosity and just wanted to share what I found.

1) When opening https://www.youtube.com/embed/rGedjDnQ9cw or another URL in the browser, it shows 'Video Unavailable, Watch on YouTube.' This matches the pattern in CouchTube.

2) However, when embedding the same URL in an HTML iframe, it works as long as the HTML is opened on a server, not locally. You can test it on [this site](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_youtubeiframe_controls).

```
<!DOCTYPE html>
<html>
<body>

<iframe width="420" height="345" src="https://www.youtube.com/embed/rGedjDnQ9cw?controls=0">
</iframe>

</body>
</html>
```

Since exporting a large YouTube playlist to a JSON file can be time-consuming, I created a bash script that checks if the videos are available for embed playback before exporting the playlist to JSON. So far, this has been working well.

**Comment by codenamek83** [comment]
Hi @ozencb 

Just to provide another update: the issue with the embedded video occurs when the CouchTube instance is accessed through a private IP address (LAN). However, when I accessed the CouchTube instance using the domain name couchtube.mydomain.com, the same videos that previously displayed errors played properly. I suspect YouTube has some sort of filtering mechanism in place, possibly to prevent embedded videos from playing on local HTML files or private intranets. So, the conclusion seems to be that CouchTube can play most videos as long as the instance is accessed via a domain name and not a private IP.

**Comment by ozencb** [comment]
Awesome work @codenamek83 thank you!

I reckon most self-hosted hobbyists would run the application behind a reverse proxy with a domain name, which should make it less of an issue but I will try to find a fix in the mean time.

Youtube Iframe API is not the easiest and cleanest thing to work with, it's behaviour is a little bit cryptic to me and there are not much community suppport around it either. So it can be a little bit of an issue to understand and troubleshoot these issues
