### ISSUE TITLE
Mounting the JSON file to the container as a persistent volume from the host

### ISSUE THREAD

**Issue by codenamek83** [ozencb/couchtube#5]
It would be beneficial if the container supported persistent storage via a bind mount from the host. This would allow you to keep the JSON file locally on the host, ensuring that any updates automatically reflect in the web UI without the need to upload it through a URL via the front-end. 

Additionally, the app seems to use an incremental count for the channel numbers. I believe it would be ideal to mirror the order in the JSON file and reset the counter each time an update is made. The channel number can be derived from the position of the channels in the JSON file.

**Comment by ozencb** [comment]
Pointing to a persistent DB file should be better, IMO, as the JSON file is just an intermediary object for users to create their lists. I will add a volume to docker compose file

**Comment by codenamek83** [comment]
That seems like a good idea. However, since we can't work directly with the database, could we also have a persistent JSON file that allows us to add or remove channels/videos? The app could monitor changes to the JSON and update accordingly. This way, we could use READONLY_MODE=true for added security.

**Comment by accforgithubtest** [comment]
Thank you creating this application - very keen to try this out.

Came here to raise the same issue. 
IMO - both the path for the db, as well as a user defined json should be volume mount-able.

**Comment by codenamek83** [comment]
Hi @ozencb 

You're awesome! I pulled the latest CouchTube image and noticed you've added support for mounting JSON and database files via persistent volumes. I tested it, and everything works perfectly. I also saw that you optimized the Dockerfile to dramatically reduce the image size, from 700 MB down to just over 30 MB. Thanks!

However, it might require a bit of fine-tuning:

1. Updates made to the videos.json file in persistent storage require recreating the container and manually deleting the database. This ensures CouchTube updates the database with the modified JSON file. I would suggest adding a manual trigger or automated monitoring to initiate the repopulation of the database file. For example, a command like /couchtube --fullscan or something similar could be used.
2. When the app runs with READONLY_MODE=TRUE, the /api/invalidate-video endpoint seems to fail. As a result, the client (browser) cannot notify the server to remove videos.

Please don't feel overwhelmed by my constant feedback. I really enjoy using this app and want to help test various use cases. I hope you don't mind :)

**Comment by ozencb** [comment]
Hi, not overwhelmed at all! I'd like to tune the app more but I cannot spare enough time, unfortunstely. I could not test latest changes thoroughly (it broke demo app 😅) but I am glad it is working for you. I will definitely work on it a bit more but in the meantime, if you know how to introduce these changes please feel free to open a pull request

**Comment by ozencb** [comment]
About previous discussions:

1. A CLI command makes sense for this case, I will try it

2. The problem with allowing invalidating code with readonly mode turned off is, anyone can then send requests to invalidate any video easily on public facing servers. In order to prevent this, we would have to implement some sort of backend check to see if the video is in fact gone, but that requires Google API tokens. Doable, but increases the initial setup hassle

**Comment by ozencb** [comment]
I added an env flag named "FULL_SCAN". It is published now

**Comment by codenamek83** [comment]
Hi @ozencb I pulled the latest image and gave it a test. The introduction of the environment variable FULL_SCAN works as expected. However, I observed the following issue:

1) A container reboot is required for CouchTube to force an update of the database. I refer to this as '**forced**' because CouchTube will perform the update regardless of whether the JSON file has been modified or not.
2) Channel numbers are incremented with every reboot because CouchTube forces an update each time. For example, if I have 10 channels, each subsequent reboot will increase the total count by 10.
3) CouchTube does not actively monitor changes to the JSON file, nor does it update the database automatically.

**For Issue 1 and 2**
1. It would be great if we could have an option to monitor the JSON file for modifications (perhaps using a timestamp or another method) before forcing an update.
2. I also feel that the channel numbering should simply reflect the order of channels in the JSON file, rather than remembering the last count and incrementing based on that value.
3. Rebooting the container to force CouchTube to update the database isn’t an issue, but having a CLI option, such as `docker exec my_container_name couchtube scan`, would be a great addition.

**For Issue 3**

1. This isn’t an issue, as a container reboot or a CLI option to force an update would work well. It could be considered for a future update.

**Comment by ozencb** [comment]
I just sent a fix for channel sequences. They should reset now with every full scan.

For the other issues, I want to create an edit page in the future where users can easily add or edit their videos, which should make any other JSON capabilities redundant, IMO

**Comment by codenamek83** [comment]
Hi @ozencb Thanks for fixing the channel sequence issue. I just tested it, and it works as expected.

IMHO, having a JSON or equivalent YAML file option should be available for power users or administrators. This would make their lives easier when automating tasks. For example, I currently have over 2,000 videos in my JSON file, and I can’t imagine populating them manually. The web UI could still be beneficial for non-tech-savvy users, so perhaps offering both options would be the best approach.

**Comment by ozencb** [comment]
Thanks a lot!

I don't think that I would be removing JSON capabilities but introduce a UI that complement already existing features, in case anyone wants to use a UI instead. But it's just a plan for the future at this point
