### ISSUE TITLE
CouchTube is playing the videos in a round-robin manner between the 4 channels in the JSON file

### ISSUE THREAD

**Issue by codenamek83** [ozencb/couchtube#7]
I'm not sure if that's the intended design, but it’s causing the next video to cycle through all the channels.

I feel it would be better if CouchTube only cycled through videos from the selected channel, kind of like how TV channels work. For example, if a user has channels like Music Videos, Science & Tech, Movies, and Documentaries, it would be nice to scope it to the user's selection. If there are other use cases, maybe adding an option to enable or disable the round-robin feature would be a good idea.

**Comment by ozencb** [comment]
Hi, this was a bug. I sent a fix for this now

**Comment by codenamek83** [comment]
Hi @ozencb Thanks for solving the issue. This has resolved the cycling between channels after each video completes.

However, the same should apply when a video is unavailable. For example, when CouchTube invalidates a video, it currently skips both the video and the channel, moving on to the next one. I feel a more natural approach would be for CouchTube to continue searching for the next available video in the user-selected channel and play it.

**Comment by ozencb** [comment]
Yup, nice catch. Sending another fix for this one now. Thanks a lot!

**Comment by codenamek83** [comment]
I just tested it, and it works perfectly now. Thank you!
